// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDnsStatic(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDnsStatic'](arg1, arg2, arg3);
}

export function AddIpStatic(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddIpStatic'](arg1, arg2, arg3);
}

export function DisableInterface(arg1) {
  return window['go']['main']['App']['DisableInterface'](arg1);
}

export function EnableInterface(arg1) {
  return window['go']['main']['App']['EnableInterface'](arg1);
}

export function FlushDns() {
  return window['go']['main']['App']['FlushDns']();
}

export function GetInterfaceConfigs() {
  return window['go']['main']['App']['GetInterfaceConfigs']();
}

export function GetInterfaceStates() {
  return window['go']['main']['App']['GetInterfaceStates']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function ReleaseDhcp() {
  return window['go']['main']['App']['ReleaseDhcp']();
}

export function RenewDhcp() {
  return window['go']['main']['App']['RenewDhcp']();
}

export function SetDhcp(arg1) {
  return window['go']['main']['App']['SetDhcp'](arg1);
}

export function SetDnsDhcp(arg1) {
  return window['go']['main']['App']['SetDnsDhcp'](arg1);
}

export function SetDnsStatic(arg1, arg2) {
  return window['go']['main']['App']['SetDnsStatic'](arg1, arg2);
}

export function SetInterfaceMetric(arg1, arg2) {
  return window['go']['main']['App']['SetInterfaceMetric'](arg1, arg2);
}

export function SetInterfaceMetricAuto(arg1) {
  return window['go']['main']['App']['SetInterfaceMetricAuto'](arg1);
}

export function SetInterfaceName(arg1, arg2) {
  return window['go']['main']['App']['SetInterfaceName'](arg1, arg2);
}

export function SetIpDhcp(arg1) {
  return window['go']['main']['App']['SetIpDhcp'](arg1);
}

export function SetIpStatic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetIpStatic'](arg1, arg2, arg3, arg4);
}

export function SetStatic(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetStatic'](arg1, arg2, arg3, arg4, arg5);
}
