// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDnsStatic(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function AddIpStatic(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function FlushDns():Promise<boolean>;

export function GetInterfaceConfigs():Promise<Array<main.InterfaceConfig>>;

export function GetInterfaceStates():Promise<Array<main.InterfaceState>>;

export function GetInterfaces():Promise<Array<main.Interface>>;

export function IsAdmin():Promise<boolean>;

export function ReleaseDhcp():Promise<boolean>;

export function RenewDhcp():Promise<boolean>;

export function SetDhcp(arg1:string):Promise<boolean>;

export function SetDnsDhcp(arg1:string):Promise<boolean>;

export function SetDnsStatic(arg1:string,arg2:string):Promise<boolean>;

export function SetInterfaceMetric(arg1:string,arg2:string):Promise<boolean>;

export function SetInterfaceMetricAuto(arg1:string):Promise<boolean>;

export function SetInterfaceName(arg1:string,arg2:string):Promise<boolean>;

export function SetIpDhcp(arg1:string):Promise<boolean>;

export function SetIpStatic(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function SetStatic(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;
